/**
 * Component Repository
 * 
 * Data access layer for components (reusable layer trees)
 * Components are stored globally and can be instanced across pages
 * Supports draft/published workflow with content hash-based change detection
 */

import { getSupabaseAdmin } from '../supabase-server';
import type { Component, Layer } from '@/types';
import { generateComponentContentHash } from '../hash-utils';

/**
 * Input data for creating a new component
 */
export interface CreateComponentData {
  name: string;
  layers: Layer[];
}

/**
 * Get all components (draft by default)
 */
export async function getAllComponents(isPublished: boolean = false): Promise<Component[]> {
  const client = await getSupabaseAdmin();
  if (!client) {
    throw new Error('Failed to initialize Supabase client');
  }
  
  const { data, error } = await client
    .from('components')
    .select('*')
    .eq('is_published', isPublished)
    .order('created_at', { ascending: false });
  
  if (error) {
    throw new Error(`Failed to fetch components: ${error.message}`);
  }
  
  return data || [];
}

/**
 * Get a single component by ID
 */
export async function getComponentById(id: string): Promise<Component | null> {
  const client = await getSupabaseAdmin();
  if (!client) {
    throw new Error('Failed to initialize Supabase client');
  }
  
  const { data, error } = await client
    .from('components')
    .select('*')
    .eq('id', id)
    .single();
  
  if (error && error.code !== 'PGRST116') {
    throw new Error(`Failed to fetch component: ${error.message}`);
  }
  
  return data;
}

/**
 * Create a new component (draft by default)
 */
export async function createComponent(
  componentData: CreateComponentData
): Promise<Component> {
  const client = await getSupabaseAdmin();
  if (!client) {
    throw new Error('Failed to initialize Supabase client');
  }
  
  // Calculate content hash
  const contentHash = generateComponentContentHash({
    name: componentData.name,
    layers: componentData.layers,
  });
  
  const { data, error } = await client
    .from('components')
    .insert({
      name: componentData.name,
      layers: componentData.layers,
      content_hash: contentHash,
      is_published: false,
      // publish_key is auto-generated by database default
    })
    .select()
    .single();
  
  if (error) {
    throw new Error(`Failed to create component: ${error.message}`);
  }
  
  return data;
}

/**
 * Update a component and recalculate content hash
 */
export async function updateComponent(
  id: string,
  updates: Partial<Pick<Component, 'name' | 'layers'>>
): Promise<Component> {
  const client = await getSupabaseAdmin();
  if (!client) {
    throw new Error('Failed to initialize Supabase client');
  }
  
  // Get current component to merge with updates
  const current = await getComponentById(id);
  if (!current) {
    throw new Error('Component not found');
  }
  
  // Merge current data with updates for hash calculation
  const finalData = {
    name: updates.name !== undefined ? updates.name : current.name,
    layers: updates.layers !== undefined ? updates.layers : current.layers,
  };
  
  // Recalculate content hash
  const contentHash = generateComponentContentHash(finalData);
  
  const { data, error } = await client
    .from('components')
    .update({
      ...updates,
      content_hash: contentHash,
      updated_at: new Date().toISOString(),
    })
    .eq('id', id)
    .select()
    .single();
  
  if (error) {
    throw new Error(`Failed to update component: ${error.message}`);
  }
  
  return data;
}

/**
 * Get a published component by publish_key
 */
export async function getPublishedComponentByPublishKey(publishKey: string): Promise<Component | null> {
  const client = await getSupabaseAdmin();
  if (!client) {
    throw new Error('Failed to initialize Supabase client');
  }
  
  const { data, error } = await client
    .from('components')
    .select('*')
    .eq('publish_key', publishKey)
    .eq('is_published', true)
    .single();
  
  if (error && error.code !== 'PGRST116') {
    throw new Error(`Failed to fetch published component: ${error.message}`);
  }
  
  return data;
}

/**
 * Publish a component (dual-record pattern like pages)
 * Creates/updates a separate published version while keeping draft untouched
 */
export async function publishComponent(draftComponentId: string): Promise<Component> {
  const client = await getSupabaseAdmin();
  if (!client) {
    throw new Error('Failed to initialize Supabase client');
  }
  
  // Get the draft component
  const draftComponent = await getComponentById(draftComponentId);
  if (!draftComponent) {
    throw new Error('Draft component not found');
  }
  
  // Check if published version already exists
  const existingPublished = await getPublishedComponentByPublishKey(draftComponent.publish_key);
  
  // Copy the draft's content_hash directly (don't recalculate to avoid mismatches)
  const publishedData = {
    name: draftComponent.name,
    layers: draftComponent.layers,
    content_hash: draftComponent.content_hash, // Copy hash from draft
    is_published: true,
    publish_key: draftComponent.publish_key,
  };
  
  if (existingPublished) {
    // Update existing published version only if content_hash changed
    if (existingPublished.content_hash !== draftComponent.content_hash) {
      const { data, error } = await client
        .from('components')
        .update(publishedData)
        .eq('id', existingPublished.id)
        .select()
        .single();
      
      if (error) {
        throw new Error(`Failed to update published component: ${error.message}`);
      }
      
      return data;
    }
    
    return existingPublished;
  } else {
    // Create new published version
    const { data, error } = await client
      .from('components')
      .insert(publishedData)
      .select()
      .single();
    
    if (error) {
      throw new Error(`Failed to create published component: ${error.message}`);
    }
    
    return data;
  }
}

/**
 * Get all unpublished components
 * A component needs publishing if:
 * - It has is_published: false (never published), OR
 * - Its draft content_hash differs from published content_hash (needs republishing)
 */
export async function getUnpublishedComponents(): Promise<Component[]> {
  const client = await getSupabaseAdmin();
  if (!client) {
    throw new Error('Failed to initialize Supabase client');
  }
  
  // Get all draft components
  const { data: draftComponents, error } = await client
    .from('components')
    .select('*')
    .eq('is_published', false)
    .order('created_at', { ascending: false });
  
  if (error) {
    throw new Error(`Failed to fetch draft components: ${error.message}`);
  }
  
  if (!draftComponents || draftComponents.length === 0) {
    return [];
  }
  
  const unpublishedComponents: Component[] = [];
  
  // Check each draft component
  for (const draftComponent of draftComponents) {
    // Check if published version exists
    const publishedComponent = await getPublishedComponentByPublishKey(draftComponent.publish_key);
    
    // If no published version exists, needs first-time publishing
    if (!publishedComponent) {
      unpublishedComponents.push(draftComponent);
      continue;
    }
    
    // Compare content hashes
    if (draftComponent.content_hash !== publishedComponent.content_hash) {
      unpublishedComponents.push(draftComponent);
    }
  }
  
  return unpublishedComponents;
}

/**
 * Get count of unpublished components
 */
export async function getUnpublishedComponentsCount(): Promise<number> {
  const components = await getUnpublishedComponents();
  return components.length;
}

/**
 * Delete a component and detach it from all layers in all page_layers records
 */
export async function deleteComponent(id: string): Promise<void> {
  const client = await getSupabaseAdmin();
  if (!client) {
    throw new Error('Failed to initialize Supabase client');
  }
  
  // First, get all page_layers records that might contain layers with this component
  const { data: pageLayersRecords, error: fetchError } = await client
    .from('page_layers')
    .select('id, layers')
    .is('deleted_at', null);
  
  if (fetchError) {
    throw new Error(`Failed to fetch page layers: ${fetchError.message}`);
  }
  
  // Detach component from layers in each record
  if (pageLayersRecords && pageLayersRecords.length > 0) {
    const updates = pageLayersRecords
      .map(record => {
        const updatedLayers = detachComponentFromLayersRecursive(record.layers || [], id);
        // Only update if layers actually changed
        if (JSON.stringify(updatedLayers) !== JSON.stringify(record.layers)) {
          return { id: record.id, layers: updatedLayers };
        }
        return null;
      })
      .filter(Boolean);
    
    // Batch update all affected records
    for (const update of updates) {
      if (update) {
        const { error: updateError } = await client
          .from('page_layers')
          .update({ 
            layers: update.layers,
            updated_at: new Date().toISOString()
          })
          .eq('id', update.id);
        
        if (updateError) {
          console.error(`Failed to update page_layers ${update.id}:`, updateError);
        }
      }
    }
  }
  
  // Finally, delete the component (both draft and published versions)
  const { error } = await client
    .from('components')
    .delete()
    .eq('id', id);
  
  if (error) {
    throw new Error(`Failed to delete component: ${error.message}`);
  }
}

/**
 * Helper function to recursively remove componentId from layers
 */
function detachComponentFromLayersRecursive(layers: Layer[], componentId: string): Layer[] {
  return layers.map(layer => {
    // Create a clean copy of the layer
    const cleanLayer = { ...layer };
    
    // If this layer uses the component, remove componentId and componentOverrides
    if (cleanLayer.componentId === componentId) {
      delete cleanLayer.componentId;
      delete cleanLayer.componentOverrides;
    }
    
    // Recursively process children
    if (cleanLayer.children && cleanLayer.children.length > 0) {
      cleanLayer.children = detachComponentFromLayersRecursive(cleanLayer.children, componentId);
    }
    
    return cleanLayer;
  });
}

