import type { Knex } from 'knex';

/**
 * Migration: Add generated_css Column to Page Versions
 * 
 * Adds a text column to store CSS generated by Tailwind Play CDN
 * for published pages to use without the CDN.
 */

export async function up(knex: Knex): Promise<void> {
  // Add generated_css column to page_versions table
  await knex.schema.table('page_versions', (table) => {
    table.text('generated_css').nullable();
  });
}

export async function down(knex: Knex): Promise<void> {
  // Remove generated_css column
  await knex.schema.table('page_versions', (table) => {
    table.dropColumn('generated_css');
  });
}


